url: https://memo330179.github.io
baseurl: ''
author: Guillermo Ramos Macias
# Site settings
title: Guilllermo Ramos Macias
email: ramosmaciasg@gmail.com
description: "A site for my personal portfolio and blog post about various things"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ramosmaciasg
  - title: bitbucket
    url: http://bitbucket.org/guillermo_ramos
  - title: github
    url: http://github.com/memo330179
  - title: linkedin
    url: https://www.linkedin.com/in/ramosmaciasg

# Postal address (add as many lines as necessary)
address:
  - line: 101 chestnut Street 1257
  - line: Berea, KY 40404

# Build settings
markdown: kramdown
permalink: pretty